# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app_user.customize_registrationform:
        class: AppBundle\UserBundle\EventListener\CustomizeRegistrationformListener
        arguments: ['@mailer', '@fos_user.util.token_generator']
        tags:
            - { name: kernel.event_subscriber }