# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.custom_mailer.sender_adress: %sender_adress%

services:
    app_user.customize_registrationform:
        class: AppBundle\UserBundle\EventListener\CustomizeRegistrationformListener
        arguments: ['@app.custom_mailer', '@fos_user.util.token_generator', '@fos_user.group_manager', '@doctrine.orm.entity_manager', '@router', '@fos_user.user_manager']
        tags:
            - { name: kernel.event_subscriber }

    app.custom_mailer:
        class: AppBundle\CustomMailer\CustomMailer
        arguments: ['@mailer', '@templating', "%app.custom_mailer.sender_adress%"]

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.change_password:
        class: AppBundle\Form\ChangePasswordFormType
        tags:
            - { name: form.type, alias: app_user_change_password }

    app.form.profile:
        class: AppBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }