# src/AppBundle/Resources/config/admin.yml

services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.course:
        class: AppBundle\Admin\CourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Kurse", label: "Kurse" }
        arguments:
            - ~
            - AppBundle\Entity\Course
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.quiz:
        class: AppBundle\Admin\QuizAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Kurse", label: "Quiz" }
        arguments:
            - ~
            - AppBundle\Entity\Quiz
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.question:
        class: AppBundle\Admin\QuestionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Kurse", label: "Quizfragen" }
        arguments:
            - ~
            - AppBundle\Entity\Question
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.answer:
        class: AppBundle\Admin\AnswerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Kurse", label: "Antworten" }
        arguments:
            - ~
            - AppBundle\Entity\Answer
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]